"""
Pydantic Schemas
"""
from schemas.admin import (
    AdminCreate,
    AdminLoginRequest,
    AdminLoginResponse,
    AdminOperationLogResponse,
    AdminResponse,
    AdminUpdate,
    BatchOperationRequest,
    BatchOperationResponse,
    PermissionTemplateCreate,
    PermissionTemplateResponse,
    PermissionTemplateUpdate,
)
from schemas.base import ApiResponse, BaseSchema, PaginatedResponse, TimestampSchema
from schemas.conversation import (
    ConversationCreate,
    ConversationDetailResponse,
    ConversationResponse,
    ConversationUpdate,
    MessageCreate,
    MessageResponse,
    UserCreate,
    UserResponse,
    UserUpdate,
    WebSocketClientMessage,
    WebSocketServerMessage,
)
from schemas.knowledge import (
    KnowledgeBaseCreate,
    KnowledgeBaseResponse,
    KnowledgeBaseUpdate,
    KnowledgeBatchImportRequest,
    KnowledgeBatchImportResponse,
    RAGQueryRequest,
    RAGQueryResponse,
)
from schemas.payment import (
    AlipayNotifyParams,
    AlipayReturnParams,
    CreatePaymentResponse,
    OrderListResponse,
    OrderQueryParams,
    PaymentChannelConfigResponse,
    PaymentOrderCreate,
    PaymentOrderDetail,
    PaymentOrderResponse,
    PaymentTransactionResponse,
    RefundRequest,
    RefundResponse,
)
from schemas.tenant import (
    BillResponse,
    QuotaUsageResponse,
    SubscriptionCreate,
    SubscriptionResponse,
    SubscriptionUpdate,
    TenantCreate,
    TenantLoginRequest,
    TenantLoginResponse,
    TenantRegisterRequest,
    TenantRegisterResponse,
    TenantResponse,
    TenantUpdate,
    TenantUpdateStatus,
    TenantWithAPIKey,
    UsageRecordResponse,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "ApiResponse",
    "PaginatedResponse",
    # Admin
    "AdminCreate",
    "AdminUpdate",
    "AdminResponse",
    "AdminLoginRequest",
    "AdminLoginResponse",
    "AdminOperationLogResponse",
    "PermissionTemplateCreate",
    "PermissionTemplateUpdate",
    "PermissionTemplateResponse",
    "BatchOperationRequest",
    "BatchOperationResponse",
    # Tenant
    "TenantCreate",
    "TenantUpdate",
    "TenantUpdateStatus",
    "TenantResponse",
    "TenantWithAPIKey",
    "TenantRegisterRequest",
    "TenantRegisterResponse",
    "TenantLoginRequest",
    "TenantLoginResponse",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionResponse",
    "UsageRecordResponse",
    "QuotaUsageResponse",
    "BillResponse",
    # Conversation
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationDetailResponse",
    "MessageCreate",
    "MessageResponse",
    "WebSocketClientMessage",
    "WebSocketServerMessage",
    # Knowledge
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseResponse",
    "RAGQueryRequest",
    "RAGQueryResponse",
    "KnowledgeBatchImportRequest",
    "KnowledgeBatchImportResponse",
    # Payment
    "PaymentOrderCreate",
    "PaymentOrderResponse",
    "PaymentOrderDetail",
    "CreatePaymentResponse",
    "PaymentTransactionResponse",
    "AlipayReturnParams",
    "AlipayNotifyParams",
    "OrderQueryParams",
    "OrderListResponse",
    "RefundRequest",
    "RefundResponse",
    "PaymentChannelConfigResponse",
]
